config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'
	get 'moderation/new_posts'
  get 'moderation/pending'
  get 'home' => 'pages/home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
	get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
	post 'create_comment' => 'posts#create_comment'
	delete 'delete_comment' => 'comments#destroy'
	resources :users
	resources :posts
	resources :topics
	resources :moderation, only: [:update]
	resources :account_activations , only: [:edit]
  resources :admin, only: [:index,:update, :destroy]
	resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :user
	has_many :posts, dependent: :destroy
	default_scope -> {order(created_at: :desc)}
	validates :theme, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	before_action :logged_in_user, only: [:index, :show]
	before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]

	def index
		@topics = Topic.all.paginate(page: params[:page])
	end

	def show
		@topic = Topic.find(params[:id])
		@posts = posts_feed.where(topic_id: @topic.id).paginate(page: params[:page])
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = current_user.topics.build(topic_params)
		if @topic.save
			flash[:success] = "Topic created!"
			redirect_to request.referrer || root_url
		else
			render 'new'
		end
	end

	def edit
		@topic = Topic.find(params[:id])
	end

	def update
		@topic = Topic.find(params[:id])
		if @topic.update_attributes(topic_params)
			flash.now[:success] = "Topic updated"
			render 'edit'
		else
			flash.now[:success] = "Something wrong. \nPlease try again later."
			render 'edit'
		end
	end

	def destroy
		@topic = Topic.find(params[:id])
		@topic.destroy
		flash[:success] = "Topic deleted"
		redirect_to request.referrer || root_url
	end

	private

	def topic_params
		params.require(:topic).permit(:theme, :description)
	end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.erb
<div class="container">
  <div class="topicHeader">
    <span class="topicHeaderHead"><h2><%= link_to topic.theme, topic_path(topic.id) %></h2></span>
    <span class="topicHeaderCount"><%= pluralize(topic.posts.where(accepted:true).count, "post") %></span>
  </div>
  <% if !topic.description.blank? %>
    <div class="topicDescription "><%= topic.description %></div>
  <% end %>
  <% if current_user.admin? %>
    <div class="topicAdminLinks">
      <%= link_to "Edit", edit_topic_path(topic.id), class: "btn btn-primary btn-sm" %>
      <%= link_to "Delete", topic_path(topic.id), method: :delete, data: {
          confirm: "The topic " + topic.theme + " will be removed. \n Are you sure?"}, class: "btn btn-danger btn-sm" %>
    </div>
  <% end %>
</div>

app/views/topics/_topic_form.html.erb
<%= form_for @topic do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :theme %>
  <%= f.text_field :theme, class: "form-control", placeholder: "Theme" %>
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/topics/edit.html.erb
<h2>Edit topic</h2>
<%= render 'topic_form' %>

app/views/topics/index.html.erb
<% if @topics.any? %>
  <%= will_paginate @topics %>
  <%= render @topics %>
  <%= will_paginate @topics %>
<% end %>

app/views/topics/new.html.erb
<h2>Create topic</h2>
<%= render 'topic_form' %>

app/views/topics/show.html.erb
<div class="container">
  <h2><%= @topic.theme %></h2>
  <div><%= @topic.description %></div>
</div>
<div>
  <% if @posts.any? %>
    <h3>Posts</h3>
    <%= will_paginate @posts %>
    <%= render @posts %>
    <%= will_paginate @posts %>
  <% end %>
</div>