config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'
	get 'moderation/new_posts'
  get 'moderation/pending'
  get 'home' => 'pages/home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
	get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
	post 'create_comment' => 'posts#create_comment'
	delete 'delete_comment' => 'comments#destroy'
	resources :users
	resources :posts
	resources :topics
	resources :moderation, only: [:update]
	resources :account_activations , only: [:edit]
  resources :admin, only: [:index,:update, :destroy]
	resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :topic
	has_many :comments, dependent: :destroy
	default_scope -> {order(created_at: :desc)}
	mount_uploader :picture, AvatarUploader
	validates :user_id, presence: true
	validates :title, presence: true
	validates :topic_id, presence: true
	validates :content, presence: true, length: {maximum: 140}
	validate :picture_size

	private

	def picture_size
		if picture.size > 5.megabytes
			errors.add(:picture, "should be less than 5MB")
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
	before_action :correct_user || :admin_user, only: [:destroy, :edit, :update]

	include PostsHelper

	def index
		@posts = posts_feed
	end

	def show
		@post = Post.find(params[:id])
		@topic = Topic.find(@post.topic_id)
		@comments = @post.comments.paginate(page: params[:page])
		@comment = Comment.new
		@post_status = post_status
	end

	def show_comments
		@comments = @post.comments
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created!"
			redirect_to root_url
		else
			@feed_items = []
			redirect_to root_url
		end
	end

	def edit
		@post = Post.find(params[:id])
		@topics = Topic.all.map {|u| [u.theme, u.id]}
	end

	def update
		@post = Post.find(params[:id])
		if @post.accepted? || @post.rejected?
			update_params = post_params.merge!({
					                                   new_post: false,
					                                   accepted: false,
					                                   pending: true,
					                                   rejected: false
			                                   })
			if @post.update_attributes(update_params)
				flash[:success] = "Post updated"
				redirect_to @post
			else
				render edit
			end
		else
			if @post.update_attributes(post_params)
				flash[:success] = "Post updated"
				redirect_to @post
			else
				render "edit"
			end
		end
	end

	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to(request.referrer || root_url)
	end

	def create_comment
		@post = Post.find(params[:id])
		@comment = @post.comments.create(comment_params.merge!({user_id: current_user.id}))
		if @comment.save
			flash[:success] = "Comment saved"
			redirect_to @post
		else
			redirect_to @post
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end

	def post_params
		params.require(:post).permit(:content, :picture, :title, :topic_id)
	end

	def correct_user
		@post = current_user.posts.find_by(id: params[:id])
		redirect_to root_url if @post.nil?
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_status
		if @post.new_post? && !@post.pending? && !@post.accepted && !@post.rejected?
			"New"
		elsif !@post.new_post? && @post.pending? && !@post.accepted? && !@post.rejected?
			"Pending"
		elsif !@post.new_post? && !@post.pending? && @post.accepted? && !@post.rejected?
			"Accepted"
		elsif !@post.new_post? && !@post.pending? && !@post.accepted? && @post.rejected?
			"Declined"
		else
			"Undefined post status"
		end
	end

	def posts_feed
		if current_user.admin?
			Post.all.paginate(page: params[:page])
		elsif current_user.moder?
			Post.where("new_post= ? OR pending= ?", true, true).paginate(page: params[:page])
		else
			Post.where("accepted", true).paginate(page: params[:page])
		end
	end
end

app/views/posts/_comment_form.html.erb
<%= form_for @comment, url: {action: "create_comment"}, html: {class: "input-group mb-3 col-md-5"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= hidden_field_tag :id, @post.id %>
  <%= f.text_area :body, placeholder: "Your comment", class: "form-control" %>
  <%= f.submit "Save", class: "btn btn-outline-secondary" %>
<% end %>

app/views/posts/_comments_feed.html.erb
<% if @comments.any? %>
  <% will_paginate @comments %>
  <%= render @comments %>
  <% will_paginate @comments %>
<% end %>

app/views/posts/_post.html.erb
<div class="userPost">
  <div class="container">

    <div class="postTimestamp">Posted by: <%= link_to post.user.name, post.user, class: "postUserName" %>, <%= time_ago_in_words(post.created_at) %> ago.</div>
    <span class="postTopicTheme">In topic: <%= link_to post.topic.theme, post.topic%></span>
    <%= link_to post.title, post, class: "postTitle" %>

    <% if current_user?(post.user)%>
      <%= link_to "delete", post, method: :delete, data: {confirm: "You sure?"}, class: "postDeleteLink btn btn-outline-danger btn-sm" %>
      <% elsif current_user.admin? %>
      <%= link_to "delete", admin_path(id: post.id), method: :delete, data: { confirm: "Are you sure?"}, class: "postDeleteLink btn btn-outline-danger btn-sm" %>
    <% end %>
    <div class="postCommentsCount">
      <%= pluralize(post.comments.count, "comment") %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= form_for(@post, url: post_path, html: {method: "patch"}, class: "form-group") do |f| %>
  <%= f.label :title, class: "col-sm-2 col-form-label col-form-label-lg" %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :topic_id, class: "col-sm-2 col-form-label col-form-label-lg" %>
  <%= f.select :topic_id, options_for_select(@topics), {}, {:class => "form-control"} %>
  <%= f.label :content, class: "col-sm-2 col-form-label col-form-label-lg" %>
  <%= f.text_area :content, class: "form-control" %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <%= will_paginate @posts %>
  <%= render @posts %>
  <%= will_paginate @posts %>
<% end %>

app/views/posts/show.html.erb
<div class="postInfo container">
  <h1 class="postHeader"><%= @post.title %></h1>
  <%= link_to @topic.theme, @topic, class: "postTopic" %>
  <% if current_user == @post.user %>
    <div class="postEditLinks">
      <%= link_to "Edit", edit_post_path, class: "btn btn-primary" %>
      <%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  <% end %>
  <div>
    <% if current_user.moder? %>
      <%= form_for(@post, url: moderation_path, html: {method: "patch"}) do |f| %>
        <%= f.radio_button :accepted, 'accept' %>
        <%= f.label :accepted_accept, 'Accept' %>
        <%= f.radio_button :accepted, 'decline', :checked => true %>
        <%= f.label :accepted_decline, 'Decline' %>
        <%= f.submit 'Save', class: "btn btn-warning postModerSave btn-sm" %>
      <% end %>
    <% end %>
    <div>
      <span class="postStatus"><%= @post_status %></span>
      <% if @post.user == current_user || current_user.admin? || current_user.moder? %>
      <% end %>
    </div>
    <div class="postContent container"><%= @post.content %></div>
  </div>
  <%= render 'comment_form' %>
  <% if @post.comments.any? %>
    <h2>Comments</h2>
    <%= render 'comments_feed' %>
  <% end %>
</div>