config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'
	get 'moderation/new_posts'
  get 'moderation/pending'
  get 'home' => 'pages/home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
	get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
	post 'create_comment' => 'posts#create_comment'
	delete 'delete_comment' => 'comments#destroy'
	resources :users
	resources :posts
	resources :topics
	resources :moderation, only: [:update]
	resources :account_activations , only: [:edit]
  resources :admin, only: [:index,:update, :destroy]
	resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_debug.html.erb
<% if Rails.env.development? %>
  <div id="debug">
    <%= debug(params) %>
  </div>
<% end %>

app/views/layouts/_dropdown_menu_logged_in.html.erb
<div class="dropdown">
  <a class=" dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to "Posts", posts_path, class: "dropdown-item" %>
    <%= link_to "Profile", current_user, class: "dropdown-item" %>
    <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
    <div class="dropdown-divider"></div>
    <% if current_user.admin? %>
      <%= link_to "Add topic", new_topic_path, class: "dropdown-item" %>
      <%= link_to "All posts", admin_index_path, class: "dropdown-item" %>
    <% elsif current_user.moder? %>
      <%= link_to "New posts", moderation_new_posts_path, class: "dropdown-item" %>
      <%= link_to "Pending posts", moderation_pending_path, class: "dropdown-item" %>
    <% end %>
    <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
  </div>
</div>

app/views/layouts/_dropdown_menu_logged_out.html.erb
<div class="dropdown">
  <a class=" dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to "Sign Up", signup_path, class: "dropdown-item" %>
    <%= link_to "Login", login_path, class: "dropdown-item" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer" class="container">
  <a href="https://github.com/BogPRo/Blog">Git Hub</a>
  <a href="https://rubyonrails.org/">Ruby on Rails</a>
  <a href="https://getbootstrap.com/">Bootstrap</a>
</footer>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
<head>
  <% provide(:title) %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<header id="header" class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Topics", topics_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
          </ul>
          <%= render 'layouts/dropdown_menu_logged_in' %>
        <% else %>
          <%= render 'layouts/dropdown_menu_logged_out' %>
        <% end %>
        </div>
  </nav>
</header>

app/views/layouts/_title.html.erb
<% provide(:full_title, 'Sign up') %>

app/views/layouts/application.html.erb
  <%= render "layouts/head" %>
  <body class="container">
  <%= render "layouts/header" %>
  <div id="content" class="container">
    <div id="flashMessages">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </div>
  <%= render "layouts/debug" %>
  <%= render "layouts/footer" %>
  </body>
</html>